all: nonStationarySpectralAnalysis.pdf
# all: figTester.pdf figTesterHighTemporalRes.pdf

# figTester.pdf: figTester.tex figTimeFreqUncertainty.tex

# figTesterHighTemporalRes.pdf: figTesterHighTemporalRes.tex figTimeFreqUncertaintyHighTemporalRes.tex

%.pdf: %.tex
	pdflatex $<

#	bibtex $*.aux
#	pdflatex $<
#	pdflatex $<
